#
#
#
set( DEPENDENCIES_LIBRARY_DIRS
   ${DEPENDENCIES_DIR}/Debug/lib
   ${DEPENDENCIES_LIBRARY_DIRS}
)


if( MULLE_C_COMPILER_ID MATCHES "^(Intel|MSVC|MSVC-Clang|MSVC-MulleClang)$")
   set( OTHER_C_FLAGS "${OTHER_C_FLAGS} /Od /Z7 /DDEBUG=1 ")
else()
   set( OTHER_C_FLAGS "${OTHER_C_FLAGS} -O0 -g -DDEBUG")
endif()
