#
#
#

message( STATUS "CMAKE_SYSTEM_NAME is ${CMAKE_SYSTEM_NAME}")

if( APPLE)
   message( STATUS "CMAKE_OSX_SYSROOT is ${CMAKE_OSX_SYSROOT}")
   message( STATUS "CMAKE_OSX_DEPLOYMENT_TARGET is ${CMAKE_OSX_DEPLOYMENT_TARGET}")
endif()

message( STATUS "CMAKE_LIBRARY_PATH is ${CMAKE_LIBRARY_PATH}")
message( STATUS "CMAKE_C_COMPILER_ID is ${CMAKE_C_COMPILER_ID}")
message( STATUS "CMAKE_CXX_COMPILER_ID is ${CMAKE_C_COMPILER_ID}")
message( STATUS "MULLE_C_COMPILER_ID is ${MULLE_C_COMPILER_ID}")
message( STATUS "MULLE_CXX_COMPILER_ID is ${MULLE_C_COMPILER_ID}")
message( STATUS "CMAKE_C_FLAGS is ${CMAKE_C_FLAGS}")
message( STATUS "CMAKE_CXX_FLAGS is ${CMAKE_CXX_FLAGS}")
