#
#
#
include_directories( BEFORE SYSTEM "${DEPENDENCIES_INCLUDE_DIR}")

link_directories( ${CMAKE_BINARY_DIR}
   ${DEPENDENCIES_LIBRARY_DIRS}
)

set( CMAKE_LIBRARY_PATH
   ${CMAKE_LIBRARY_PATH}
   ${DEPENDENCIES_LIBRARY_DIRS}
)


set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OTHER_C_FLAGS} ${UNWANTED_C_WARNINGS}")
set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OTHER_C_FLAGS} ${UNWANTED_C_WARNINGS}")


if( "${MULLE_LANGUAGE}" STREQUAL "ObjC")
   include( CommonObjC)
   include( DebugObjC)
   set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${UNWANTED_OBJC_WARNINGS}")
   set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${UNWANTED_OBJC_WARNINGS}")
endif()


message(STATUS "CMAKE_SYSTEM_NAME is ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_LIBRARY_PATH is ${CMAKE_LIBRARY_PATH}")
message(STATUS "CMAKE_C_COMPILER_ID is ${CMAKE_C_COMPILER_ID}")
message(STATUS "CMAKE_CXX_COMPILER_ID is ${CMAKE_C_COMPILER_ID}")
message(STATUS "MULLE_C_COMPILER_ID is ${MULLE_C_COMPILER_ID}")
message(STATUS "MULLE_CXX_COMPILER_ID is ${MULLE_C_COMPILER_ID}")
message(STATUS "CMAKE_C_FLAGS is ${CMAKE_C_FLAGS}")
message(STATUS "CMAKE_CXX_FLAGS is ${CMAKE_CXX_FLAGS}")
